// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://hpymunjkpwmmnvdjmynb.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhweW11bmprcHdtbW52ZGpteW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1ODUyNjAsImV4cCI6MjA4NDE2MTI2MH0.4lgtATTZupeIbvotBo24ghbX7lvAIMRWea2nBeSXZ5k';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});